<template>
	<div class="aioseo-search-appearance-advanced">
		<core-card
			slug="searchAdvanced"
			:header-text="strings.advanced"
		>
			<core-settings-row
				:name="strings.globalRobotsMeta"
			>
				<template #content>
					<core-robots-meta
						:options="options.searchAppearance.advanced.globalRobotsMeta"
						global
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.sitelinks"
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.sitelinks"
						:name="strings.sitelinks"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.sitelinksDescription }}
					</div>
				</template>
			</core-settings-row>

			<!--core-settings-row
				:name="strings.noIndexEmptyCat"
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.noIndexEmptyCat"
						name="noIndexEmptyCat"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.removeStopWords"
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.removeStopWords"
						name="removeStopWords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>
				</template>
			</core-settings-row-->

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions')"
				:name="strings.autogenerateDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.deprecated.searchAppearance.advanced.autogenerateDescriptions"
						name="autogenerateDescriptions"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('useContentForAutogeneratedDescriptions') && (!internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions') || options.deprecated.searchAppearance.advanced.autogenerateDescriptions)"
				:name="strings.useContentForAutogeneratedDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.deprecated.searchAppearance.advanced.useContentForAutogeneratedDescriptions"
						name="useContentForAutogeneratedDescriptions"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('runShortcodesInDescription') && (!internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions') || options.deprecated.searchAppearance.advanced.autogenerateDescriptions)"
				:name="strings.runShortcodesInDescription"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.deprecated.searchAppearance.advanced.runShortcodesInDescription"
						name="runShortcodesInDescription"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.noPaginationForCanonical"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.noPaginationForCanonical"
						name="noPaginationForCanonical"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<!--core-settings-row>
				<template #name>
					{{ strings.removeCatBase }}
					<core-pro-badge
						v-if="isUnlicensed"
					/>
				</template>

				<template #content>
					<base-radio-toggle
						:disabled="isUnlicensed"
						v-model="removeCatBase"
						name="removeCatBase"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<core-alert
						class="inline-upsell"
						v-if="isUnlicensed"
						type="blue"
					>
						<div v-html="strings.removeCatBaseUpsell" />
					</core-alert>
				</template>
			</core-settings-row-->

			<!--core-settings-row>
				<template #name>
					{{ strings.autoAddImageAltTags }}
					<core-pro-badge
						v-if="isUnlicensed"
					/>
				</template>

				<template #content>
					<base-radio-toggle
						:disabled="isUnlicensed"
						v-model="autoAddImageAltTags"
						name="autoAddImageAltTags"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<core-alert
						class="inline-upsell"
						v-if="isUnlicensed"
						type="blue"
					>
						<div v-html="strings.autoAddImageAltTagsUpsell" />
					</core-alert>
				</template>
			</core-settings-row-->

			<core-settings-row
				:name="strings.useKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useKeywords"
						name="useKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useKeywordsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.useCategoriesForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useCategoriesForMetaKeywords"
						name="useCategoriesForMetaKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useCategoriesDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.useTagsForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useTagsForMetaKeywords"
						name="useTagsForMetaKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useTagsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.dynamicallyGenerateKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.dynamicallyGenerateKeywords"
						name="dynamicallyGenerateKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.dynamicallyGenerateDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				id="description-format"
				v-if="internalOptions.internal.deprecatedOptions.includes('descriptionFormat')"
				:name="strings.descriptionFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="description-format"
						v-model="options.deprecated.searchAppearance.global.descriptionFormat"
						:line-numbers="false"
						single
						:show-tags-description="false"
						tags-context="descriptionFormat"
						:default-tags="[
							'description',
							'site_title',
							'tagline'
						]"
						:show-all-tags-link="true"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<core-alert
						class="description-notice"
						v-if="!options.deprecated.searchAppearance.global.descriptionFormat.includes('#description')"
						type="red"
					>
						{{ strings.descriptionTagRequired }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.pagedFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="paged-format"
						v-model="options.searchAppearance.advanced.pagedFormat"
						:line-numbers="false"
						single
						tags-context="pagedFormat"
						:default-tags="[
							'page_number'
						]"
						:show-all-tags-link="false"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<div class="aioseo-description">
						{{ strings.pagedFormatDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('excludePosts')"
				:name="strings.excludePostsPages"
				class="aioseo-exclude-pages-posts"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="options.deprecated.searchAppearance.advanced"
						type="posts"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('excludeTerms')"
				:name="strings.excludeTerms"
				class="aioseo-exclude-terms"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="options.deprecated.searchAppearance.advanced"
						type="terms"
					/>
				</template>
			</core-settings-row>
		</core-card>
	</div>
</template>

<script>
import { mapGetters, mapState } from 'vuex'
export default {
	data () {
		return {
			emptyString : '',
			strings     : {
				advanced                               : this.$t.__('Advanced Settings', this.$td),
				globalRobotsMeta                       : this.$t.__('Global Robots Meta', this.$td),
				noIndexEmptyCat                        : this.$t.__('Noindex Empty Category and Tag Archives', this.$td),
				removeStopWords                        : this.$t.__('Remove Stopwords from Permalinks', this.$td),
				removeCatBase                          : this.$t.__('Remove Category Base Prefix', this.$td),
				// Translators: 1 - The plugin short name name ("AIOSEO"), 2 - "Learn more".
				removeCatBaseUpsell                    : this.$t.sprintf(this.$t.__('This feature is only for licensed %1$s users. %2$s', this.$td), `<strong>${process.env.VUE_APP_SHORT_NAME} Pro</strong>`, this.$links.getUpsellLink('search-appearance-advanced', this.$constants.GLOBAL_STRINGS.learnMore, 'remove-category-base-prefix', true)),
				autoAddImageAltTags                    : this.$t.__('Automatically Add Missing Image Alt / Title Tags', this.$td),
				// Translators: 1 - The plugin short name name ("AIOSEO"), 2 - "Learn more".
				autoAddImageAltTagsUpsell              : this.$t.sprintf(this.$t.__('This feature is only for licensed %1$s users. %2$s', this.$td), `<strong>${process.env.VUE_APP_SHORT_NAME} Pro</strong>`, this.$links.getUpsellLink('search-appearance-advanced', this.$constants.GLOBAL_STRINGS.learnMore, 'automatically-add-missing-image-tags', true)),
				autogenerateDescriptions               : this.$t.__('Autogenerate Descriptions', this.$td),
				useContentForAutogeneratedDescriptions : this.$t.__('Use Content for Autogenerated Descriptions', this.$td),
				runShortcodesInDescription             : this.$t.__('Run Shortcodes in Description', this.$td),
				noPaginationForCanonical               : this.$t.__('No Pagination for Canonical URLs', this.$td),
				useKeywords                            : this.$t.__('Use Meta Keywords', this.$td),
				useKeywordsDescription                 : this.$t.__('This option allows you to toggle the use of Meta Keywords throughout the whole of the site.', this.$td),
				useCategoriesForMetaKeywords           : this.$t.__('Use Categories for Meta Keywords', this.$td),
				useCategoriesDescription               : this.$t.__('Check this if you want your categories for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', this.$td),
				useTagsForMetaKeywords                 : this.$t.__('Use Tags for Meta Keywords', this.$td),
				useTagsDescription                     : this.$t.__('Check this if you want your tags for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', this.$td),
				dynamicallyGenerateKeywords            : this.$t.__('Dynamically Generate Meta Keywords', this.$td),
				dynamicallyGenerateDescription         : this.$t.__('Check this if you want your keywords on your Posts page (set in WordPress under Settings, Reading, Front Page Displays) and your archive pages to be dynamically generated from the keywords of the posts showing on that page. If unchecked, it will use the keywords set in the edit page screen for the posts page.', this.$td),
				pagedFormat                            : this.$t.__('Paged Format', this.$td),
				pagedFormatDescription                 : this.$t.__('This string gets appended to the titles and descriptions of paginated pages (like term or archive pages).', this.$td),
				descriptionFormat                      : this.$t.__('Description Format', this.$td),
				excludePostsPages                      : this.$t.__('Exclude Posts / Pages', this.$td),
				excludeTerms                           : this.$t.__('Exclude Terms', this.$td),
				sitelinks                              : this.$t.__('Enable Sitelinks Search Box', this.$td),
				// Translators: 1 - The plugin name ("All in One SEO").
				sitelinksDescription                   : this.$t.sprintf(this.$t.__('Choose whether %1$s should output the required schema markup that Google needs to generate a sitelinks search box.', this.$td), process.env.VUE_APP_SHORT_NAME),
				descriptionTagRequired                 : this.$t.__('A Description tag is required in order to properly display your meta descriptions on your site.', this.$td)
			}
		}
	},
	computed : {
		...mapGetters([ 'settings', 'isUnlicensed' ]),
		...mapState([ 'options', 'internalOptions' ]),
		removeCatBase : {
			get () {
				return this.$isPro ? this.options.searchAppearance.advanced.removeCatBase : false
			},
			set (newValue) {
				this.options.searchAppearance.advanced.removeCatBase = newValue
			}
		},
		autoAddImageAltTags : {
			get () {
				return !this.isUnlicensed ? this.options.searchAppearance.advanced.autoAddImageAltTags : false
			},
			set (newValue) {
				this.options.searchAppearance.advanced.autoAddImageAltTags = newValue
			}
		}
	}
}
</script>

<style lang="scss">
.aioseo-search-appearance-advanced {
	.inline-upsell {
		display: inline-flex;

		margin-top: 20px;
	}

	.description-format,
	.paged-format {
		.add-tags {
			margin-top: 0;
		}
	}

	.description-notice {
		margin-top: 10px;
	}
}
</style>