<template>
	<div class="aioseo-search-appearance-advanced">
		<core-card
			slug="searchAdvanced"
			:header-text="strings.advanced"
		>
			<core-settings-row
				:name="strings.globalRobotsMeta"
			>
				<template #content>
					<core-robots-meta
						:options="options.searchAppearance.advanced.globalRobotsMeta"
						global
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.sitelinks"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.sitelinks"
						:name="strings.sitelinks"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.sitelinksDescription }}
					</div>
				</template>
			</core-settings-row>

			<!--core-settings-row
				:name="strings.noIndexEmptyCat"
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.noIndexEmptyCat"
						name="noIndexEmptyCat"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.removeStopWords"
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.removeStopWords"
						name="removeStopWords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>
				</template>
			</core-settings-row-->

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions')"
				:name="strings.autogenerateDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.deprecated.searchAppearance.advanced.autogenerateDescriptions"
						name="autogenerateDescriptions"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('useContentForAutogeneratedDescriptions') && (!internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions') || options.deprecated.searchAppearance.advanced.autogenerateDescriptions)"
				:name="strings.useContentForAutogeneratedDescriptions"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.deprecated.searchAppearance.advanced.useContentForAutogeneratedDescriptions"
						name="useContentForAutogeneratedDescriptions"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.noPaginationForCanonical"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.noPaginationForCanonical"
						name="noPaginationForCanonical"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.useKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useKeywords"
						name="useKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useKeywordsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.useCategoriesForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useCategoriesForMetaKeywords"
						name="useCategoriesForMetaKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useCategoriesDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.useTagsForMetaKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.useTagsForMetaKeywords"
						name="useTagsForMetaKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.useTagsDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.useKeywords"
				:name="strings.dynamicallyGenerateKeywords"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.dynamicallyGenerateKeywords"
						name="dynamicallyGenerateKeywords"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.dynamicallyGenerateDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				id="description-format"
				v-if="internalOptions.internal.deprecatedOptions.includes('descriptionFormat')"
				:name="strings.descriptionFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="description-format"
						v-model="options.deprecated.searchAppearance.global.descriptionFormat"
						:line-numbers="false"
						single
						:show-tags-description="false"
						tags-context="descriptionFormat"
						:default-tags="[
							'description',
							'site_title',
							'tagline'
						]"
						:show-all-tags-link="true"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<core-alert
						class="description-notice"
						v-if="!options.deprecated.searchAppearance.global.descriptionFormat.includes('#description')"
						type="red"
					>
						{{ strings.descriptionTagRequired }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.runShortcodes"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.runShortcodes"
						name="runShortcodes"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.off, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.on, value: true }
						]"
					/>

					<core-alert
						class="run-shortcodes-alert"
						v-if="options.searchAppearance.advanced.runShortcodes"
						type="yellow"
						v-html="strings.runShortcodesWarning"
					/>

					<div class="aioseo-description" v-html="strings.runShortcodesDescription"/>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.pagedFormat"
				align
			>
				<template #content>
					<core-html-tags-editor
						class="paged-format"
						v-model="options.searchAppearance.advanced.pagedFormat"
						:line-numbers="false"
						single
						tags-context="pagedFormat"
						:default-tags="[
							'page_number'
						]"
						:show-all-tags-link="false"
					>
						<template #tags-description>
							{{ emptyString }}
						</template>
					</core-html-tags-editor>

					<div class="aioseo-description">
						{{ strings.pagedFormatDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('excludePosts')"
				:name="strings.excludePostsPages"
				class="aioseo-exclude-pages-posts"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="options.deprecated.searchAppearance.advanced"
						type="posts"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="internalOptions.internal.deprecatedOptions.includes('excludeTerms')"
				:name="strings.excludeTerms"
				class="aioseo-exclude-terms"
				align
			>
				<template #content>
					<core-exclude-posts
						:options="options.deprecated.searchAppearance.advanced"
						type="terms"
					/>
				</template>
			</core-settings-row>
		</core-card>

		<core-card
			class="aioseo-rss-content-advanced"
			slug="searchAdvancedCrawlCleanup"
			:toggles="options.searchAppearance.advanced.crawlCleanup.enable"
		>
			<template #header>
				<base-toggle
					v-model="options.searchAppearance.advanced.crawlCleanup.enable"
				/>

				{{ strings.crawlCleanup }}

				<core-tooltip
					v-if="!options.searchAppearance.advanced.crawlCleanup.enable"
				>
					<svg-circle-question-mark />

					<template #tooltip>
						{{ strings.crawlCleanupDescription }}

						<span
							v-html="$links.getDocLink($constants.GLOBAL_STRINGS.learnMore, 'crawlCleanup', true)"
						/>
					</template>
				</core-tooltip>
			</template>

			<div class="aioseo-settings-row aioseo-section-description">
				{{ strings.crawlCleanupDescription }}

				<span
					v-html="$links.getDocLink($constants.GLOBAL_STRINGS.learnMore, 'crawlCleanup', true)"
				/>
			</div>

			<core-settings-row
				:name="strings.removeUnrecognizedQueryArgs"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.removeUnrecognizedQueryArgs"
						name="removeUnrecognizedQueryArgs"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.no, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.yes, value: true }
						]"
					/>

					<div
						class="aioseo-description"
						v-if="!options.searchAppearance.advanced.crawlCleanup.removeUnrecognizedQueryArgs"
					>
						{{ strings.removeUnrecognizedQueryArgsDescription }}
						{{ strings.removeUnrecognizedQueryArgsAlert }}
					</div>

					<core-alert
						v-if="options.searchAppearance.advanced.crawlCleanup.removeUnrecognizedQueryArgs"
						type="yellow"
					>
						{{ strings.removeUnrecognizedQueryArgsAlert }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="options.searchAppearance.advanced.crawlCleanup.removeUnrecognizedQueryArgs"
				:name="strings.allowedQueryArgs"
			>
				<template #content>
					<base-textarea
						:minHeight="200"
						:maxHeight="200"
						v-model="options.searchAppearance.advanced.crawlCleanup.allowedQueryArgs"
					/>

					<div
						class="aioseo-description"
						v-html="strings.allowedQueryArgsDescription"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				id="crawl-content-global-feed"
				:name="strings.globalFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.global"
						name="global"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-if="options.searchAppearance.advanced.crawlCleanup.feeds.global"
					>
						{{ strings.globalFeedDescription }}
						{{ strings.disableGlobalFeedAlert }}

						<div class="rss-link">
							<a
								:href="$aioseo.urls.feeds.global"
								target="_blank"
							>{{ strings.openYourRssFeed }}</a>

							<a
								class="no-underline"
								:href="$aioseo.urls.feeds.global"
								target="_blank"
							>&nbsp;<svg-external /></a>
						</div>
					</div>

					<core-alert
						v-if="!options.searchAppearance.advanced.crawlCleanup.feeds.global"
						type="red"
					>
						{{ strings.disableGlobalFeedAlert }}
					</core-alert>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.globalCommentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.globalComments"
						name="globalComments"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.globalCommentsFeedDescription }}
					</div>

					<div class="aioseo-description"
						v-if="options.searchAppearance.advanced.crawlCleanup.feeds.globalComments"
					>
						<a
							:href="$aioseo.urls.feeds.globalComments"
							target="_blank"
						>{{ strings.openYourCommentsRssFeed }}</a>
						<a
							class="no-underline"
							:href="$aioseo.urls.feeds.globalComments"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="$aioseo.data.staticBlogPage"
				:name="strings.staticBlogPageFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.staticBlogPage"
						name="staticBlogPage"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.staticBlogPageFeedDescription }}
					</div>

					<div class="aioseo-description"
						v-if="options.searchAppearance.advanced.crawlCleanup.feeds.staticBlogPage"
					>
						<a
							:href="$aioseo.urls.feeds.staticBlogPage"
							target="_blank"
						>{{ strings.openYourStaticBlogPageFeed }}</a>

						<a
							class="no-underline"
							:href="$aioseo.urls.feeds.staticBlogPage"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.authorsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.authors"
						name="authors"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.authorsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.postCommentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.postComments"
						name="postComments"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.postCommentsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.searchFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.search"
						name="search"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.searchFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.attachmentsFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.attachments"
						name="attachments"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.attachmentsFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.paginatedFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.paginated"
						name="paginated"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description">
						{{ strings.paginatedFeedDescription }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				v-if="$aioseo.postData.archives.length"
				:name="strings.postTypesFeed"
			>
				<template #content>
					<base-checkbox
						size="medium"
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.archives.all"
					>
						{{ strings.includeAllPostTypes }}
					</base-checkbox>

					<core-post-type-options
						v-if="!options.searchAppearance.advanced.crawlCleanup.feeds.archives.all"
						:options="options.searchAppearance.advanced.crawlCleanup.feeds"
						type="archives"
					/>

					<div class="aioseo-description">
						{{ strings.selectPostTypes }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.taxonomiesFeed"
			>
				<template #content>
					<base-checkbox
						size="medium"
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.taxonomies.all"
					>
						{{ strings.includeAllTaxonomies }}
					</base-checkbox>

					<core-post-type-options
						v-if="!options.searchAppearance.advanced.crawlCleanup.feeds.taxonomies.all"
						:options="options.searchAppearance.advanced.crawlCleanup.feeds"
						type="taxonomies"
					/>

					<div class="aioseo-description">
						{{ strings.selectTaxonomies }}
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.atomFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.atom"
						name="atom"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-html="strings.atomFeedDescription"
					/>

					<div class="aioseo-description"
						v-if="options.searchAppearance.advanced.crawlCleanup.feeds.atom"
					>
						<a
							:href="$aioseo.urls.feeds.atom"
							target="_blank"
						>{{ strings.openYourAtomFeed }}</a>
						<a
							class="no-underline"
							:href="$aioseo.urls.feeds.atom"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>

			<core-settings-row
				:name="strings.rdfFeed"
				align
			>
				<template #content>
					<base-radio-toggle
						v-model="options.searchAppearance.advanced.crawlCleanup.feeds.rdf"
						name="rdf"
						:options="[
							{ label: $constants.GLOBAL_STRINGS.disabled, value: false, activeClass: 'dark' },
							{ label: $constants.GLOBAL_STRINGS.enabled, value: true }
						]"
					/>

					<div class="aioseo-description"
						v-html="strings.rdfFeedDescription"
					/>

					<div class="aioseo-description"
						v-if="options.searchAppearance.advanced.crawlCleanup.feeds.rdf"
					>
						<a
							:href="$aioseo.urls.feeds.rdf"
							target="_blank"
						>{{ strings.openYourRdfFeed }}</a>
						<a
							class="no-underline"
							:href="$aioseo.urls.feeds.rdf"
							target="_blank"
						>&nbsp;<svg-external /></a>
					</div>
				</template>
			</core-settings-row>
		</core-card>
	</div>
</template>

<script>
import { mapState } from 'vuex'
import BaseCheckbox from '@/vue/components/common/base/Checkbox'
import BaseRadioToggle from '@/vue/components/common/base/RadioToggle'
import BaseTextarea from '@/vue/components/common/base/Textarea'
import CoreAlert from '@/vue/components/common/core/alert/Index.vue'
import CoreCard from '@/vue/components/common/core/Card'
import CoreExcludePosts from '@/vue/components/common/core/ExcludePosts'
import CoreHtmlTagsEditor from '@/vue/components/common/core/HtmlTagsEditor'
import CorePostTypeOptions from '@/vue/components/common/core/PostTypeOptions'
import CoreRobotsMeta from '@/vue/components/common/core/RobotsMeta'
import CoreSettingsRow from '@/vue/components/common/core/SettingsRow'
import CoreTooltip from '@/vue/components/common/core/Tooltip'
import SvgCircleQuestionMark from '@/vue/components/common/svg/circle/QuestionMark'
import SvgExternal from '@/vue/components/common/svg/External'
export default {
	components : {
		BaseCheckbox,
		BaseRadioToggle,
		BaseTextarea,
		CoreAlert,
		CoreCard,
		CoreExcludePosts,
		CoreHtmlTagsEditor,
		CorePostTypeOptions,
		CoreRobotsMeta,
		CoreSettingsRow,
		CoreTooltip,
		SvgCircleQuestionMark,
		SvgExternal
	},
	data () {
		return {
			emptyString : '',
			strings     : {
				advanced                               : this.$t.__('Advanced Settings', this.$td),
				globalRobotsMeta                       : this.$t.__('Global Robots Meta', this.$td),
				noIndexEmptyCat                        : this.$t.__('Noindex Empty Category and Tag Archives', this.$td),
				removeStopWords                        : this.$t.__('Remove Stopwords from Permalinks', this.$td),
				autogenerateDescriptions               : this.$t.__('Autogenerate Descriptions', this.$td),
				useContentForAutogeneratedDescriptions : this.$t.__('Use Content for Autogenerated Descriptions', this.$td),
				runShortcodes                          : this.$t.__('Run Shortcodes', this.$td),
				runShortcodesDescription               : this.$t.sprintf(
					// Translators: 1 - The short plugin name ("AIOSEO"), 2 - "Learn More" link.
					this.$t.__('This option allows you to control whether %1$s should parse shortcodes when generating data such as the SEO title/meta description. Enabling this setting may cause conflicts with third-party plugins/themes. %2$s', this.$td),
					import.meta.env.VITE_SHORT_NAME,
					this.$links.getDocLink(this.$constants.GLOBAL_STRINGS.learnMore, 'runningShortcodes', true)
				),
				runShortcodesWarning : this.$t.sprintf(
					// Translators: 1 - "Learn More" link.
					this.$t.__('NOTE: Enabling this setting may cause conflicts with third-party plugins/themes. %1$s', this.$td),
					this.$links.getDocLink(this.$constants.GLOBAL_STRINGS.learnMore, 'runningShortcodes', true)
				),
				noPaginationForCanonical               : this.$t.__('No Pagination for Canonical URLs', this.$td),
				useKeywords                            : this.$t.__('Use Meta Keywords', this.$td),
				useKeywordsDescription                 : this.$t.__('This option allows you to toggle the use of Meta Keywords throughout the whole of the site.', this.$td),
				useCategoriesForMetaKeywords           : this.$t.__('Use Categories for Meta Keywords', this.$td),
				useCategoriesDescription               : this.$t.__('Check this if you want your categories for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', this.$td),
				useTagsForMetaKeywords                 : this.$t.__('Use Tags for Meta Keywords', this.$td),
				removeUnrecognizedQueryArgs            : this.$t.__('Remove Query Args', this.$td),
				removeUnrecognizedQueryArgsDescription : this.$t.__('Enable this option to remove any unrecognized query args from your site.', this.$td),
				removeUnrecognizedQueryArgsAlert       : this.$t.__('This will help prevent search engines from crawling every variation of your pages with all the unrecognized query arguments. Only enable this if you understand exactly what it does as it can have a significant impact on your site.', this.$td),
				allowedQueryArgs                       : this.$t.__('Allowed Query Args', this.$td),
				allowedQueryArgsDescription            : this.$t.sprintf(
					// Translators: 1 - "Learn More" link.
					this.$t.__('Add any query args that you want to allow, one per line. You can also use regular expressions here for advanced use. All query args that are used by WordPress Core (e.g. "s" for search pages) are automatically whitelisted by default. %1$s', this.$td),
					this.$links.getDocLink(this.$constants.GLOBAL_STRINGS.learnMore, 'crawlCleanup', true)
				),
				useTagsDescription             : this.$t.__('Check this if you want your tags for a given post used as the Meta Keywords for this post (in addition to any keywords you specify on the Edit Post screen).', this.$td),
				dynamicallyGenerateKeywords    : this.$t.__('Dynamically Generate Meta Keywords', this.$td),
				dynamicallyGenerateDescription : this.$t.__('Check this if you want your keywords on your Posts page (set in WordPress under Settings, Reading, Front Page Displays) and your archive pages to be dynamically generated from the keywords of the posts showing on that page. If unchecked, it will use the keywords set in the edit page screen for the posts page.', this.$td),
				pagedFormat                    : this.$t.__('Paged Format', this.$td),
				pagedFormatDescription         : this.$t.__('This string gets appended to the titles and descriptions of paginated pages (like term or archive pages).', this.$td),
				descriptionFormat              : this.$t.__('Description Format', this.$td),
				excludePostsPages              : this.$t.__('Exclude Posts / Pages', this.$td),
				excludeTerms                   : this.$t.__('Exclude Terms', this.$td),
				sitelinks                      : this.$t.__('Enable Sitelinks Search Box', this.$td),
				sitelinksDescription           : this.$t.sprintf(
					// Translators: 1 - The plugin name ("All in One SEO").
					this.$t.__('Choose whether %1$s should output the required schema markup that Google needs to generate a sitelinks search box.', this.$td),
					import.meta.env.VITE_SHORT_NAME
				),
				descriptionTagRequired        : this.$t.__('A Description tag is required in order to properly display your meta descriptions on your site.', this.$td),
				crawlCleanup                  : this.$t.__('Crawl Cleanup', this.$td),
				crawlCleanupDescription       : this.$t.__('Removing unrecognized query arguments from URLs and disabling unnecessary RSS feeds can help save search engine crawl quota and speed up content indexing for larger sites. If you choose to disable any feeds, those feed links will automatically redirect to your homepage or applicable archive page.', this.$td),
				globalFeed                    : this.$t.__('Global RSS Feed', this.$td),
				globalFeedDescription         : this.$t.__('The global RSS feed is how users subscribe to any new content that has been created on your site.', this.$td),
				openYourRssFeed               : this.$t.__('Open Your RSS Feed', this.$td),
				disableGlobalFeedAlert        : this.$t.__('Disabling the global RSS feed is NOT recommended. This will prevent users from subscribing to your content and can hurt your SEO rankings.', this.$td),
				globalCommentsFeed            : this.$t.__('Global Comments RSS Feed', this.$td),
				globalCommentsFeedDescription : this.$t.__('The global comments feed allows users to subscribe to any new comments added to your site.', this.$td),
				openYourCommentsRssFeed       : this.$t.__('Open Your Comments RSS Feed', this.$td),
				staticBlogPageFeed            : this.$t.__('Static Posts Page Feed', this.$td),
				staticBlogPageFeedDescription : this.$t.__('The static posts page feed allows users to subscribe to any new content added to your blog page.', this.$td),
				openYourStaticBlogPageFeed    : this.$t.__('Open Your Static Posts Page RSS Feed', this.$td),
				authorsFeed                   : this.$t.__('Author Feeds', this.$td),
				authorsFeedDescription        : this.$t.__('The authors feed allows your users to subscribe to any new content written by a specific author.', this.$td),
				postCommentsFeed              : this.$t.__('Post Comment Feeds', this.$td),
				postCommentsFeedDescription   : this.$t.__('The post comments feed allows your users to subscribe to any new comments on a specific page or post.', this.$td),
				searchFeed                    : this.$t.__('Search Feed', this.$td),
				searchFeedDescription         : this.$t.__('The search feed description allows visitors to subscribe to your content based on a specific search term.', this.$td),
				attachmentsFeed               : this.$t.__('Attachments Feed', this.$td),
				attachmentsFeedDescription    : this.$t.__('The attachments feed allows users to subscribe to any changes to your site made to media file categories.', this.$td),
				postTypesFeed                 : this.$t.__('Post Type Archive Feeds', this.$td),
				includeAllPostTypes           : this.$t.__('Include All Post Type Archives', this.$td),
				selectPostTypes               : this.$t.__('Select which post type archives should include an RSS feed. This only applies to post types that include an archive page.', this.$td),
				taxonomiesFeed                : this.$t.__('Taxonomy Feeds', this.$td),
				includeAllTaxonomies          : this.$t.__('Include All Taxonomies', this.$td),
				selectTaxonomies              : this.$t.__('Select which Taxonomies should include an RSS feed.', this.$td),
				atomFeed                      : this.$t.__('Atom Feed', this.$td),
				atomFeedDescription           : this.$t.sprintf(
					// Translators: 1 - Learn more link.
					this.$t.__('This is a global feed of your site output in the Atom format. %1$s', this.$td),
					this.$links.getPlainLink(this.$constants.GLOBAL_STRINGS.learnMore, 'http://www.atomenabled.org/', true)
				),
				openYourAtomFeed   : this.$t.__('Open Your Atom Feed', this.$td),
				rdfFeed            : this.$t.__('RDF/RSS 1.0 Feed', this.$td),
				rdfFeedDescription : this.$t.sprintf(
					// Translators: 1 - Learn more link.
					this.$t.__('This is a global feed of your site output in the RDF/RSS 1.0 format. %1$s', this.$td),
					this.$links.getPlainLink(this.$constants.GLOBAL_STRINGS.learnMore, 'https://web.resource.org/rss/1.0/', true)
				),
				openYourRdfFeed          : this.$t.__('Open Your RDF Feed', this.$td),
				paginatedFeed            : this.$t.__('Paginated RSS Feeds', this.$td),
				paginatedFeedDescription : this.$t.__('The paginated RSS feeds are for any posts or pages that are paginated.', this.$td)
			}
		}
	},
	computed : {
		...mapState([ 'options', 'internalOptions' ])
	}
}
</script>

<style lang="scss">
.aioseo-search-appearance-advanced {
	.description-format,
	.paged-format {
		.add-tags {
			margin-top: 0;
		}
	}

	.description-notice {
		margin-top: 10px;
	}

	.run-shortcodes-alert {
		margin-top: 12px;
	}

	svg.aioseo-external {
		width: 14px;
		height: 14px;
		margin-right: 10px;
	}

	.aioseo-alert {
		margin-top: 10px;
	}

	.aioseo-rss-content-advanced {
		.aioseo-settings-row {
			.aioseo-col {
				padding-top: 0;
			}
		}

		.aioseo-description {
			p {
				font-size: 14px;
				line-height: 1.8;
				margin: 8px 0 0;
			}

			div.rss-link {
				margin: 8px 0 0;
			}
		}
	}
}
</style>