export default {
	pong            : true,
	loaded          : false,
	internalOptions : {},
	options         : {},
	dynamicOptions  : {},
	networkOptions  : {},
	settings        : {},
	notifications   : {
		active    : [],
		new       : [],
		dismissed : [],
		force     : false
	},
	currentPost       : {},
	helpPanel         : {},
	tags              : {},
	backups           : [],
	addons            : [],
	license           : {},
	plugins           : {},
	showNotifications : false,
	loading           : false,
	analyzer          : null,
	analyzing         : false,
	analyzeError      : null,
	htaccessError     : null,
	isDirty           : false
}