export default {
	data () {
		return {
			strings : {
				seoScoresCard           : this.$t.__('SEO Scores', this.$td),
				seoScoresTooltip        : this.$t.__('The following charts contain scores to help boost your SEO rankings based on SEO best-practices. The headline analysis score shows the relative importance of factors such as word choice, and length in your post title. The TruSEO score shows the relative importance of factors like keyword density, title tag optimization, and meta description for your entire post.', this.$td),
				focusKeywordsCard       : this.$t.__('Focus Keyphrase Trends', this.$td),
				focusKeywordsTooltip    : this.$t.__('This graph shows how your focus keyphrase is trending over time for this specific post. This can help you monitor the impact of changes made to this post, such as updates to the content. As a result, you\'ll be able to see which changes are having the most positive or negative impact on your page\'s performance.', this.$td),
				seoMetaCard             : this.$t.__('SEO Meta', this.$td),
				seoMetaTooltip          : this.$t.__('SEO meta data refers to information about a web page that is not visible to users, but is used by search engines to understand the content and context of the page. The following items are a few of the most important items.', this.$td),
				speedTestCard           : this.$t.__('Speed Test', this.$td),
				speedTestTooltip        : this.$t.__('Our Speed Test results for desktop and mobile measure the performance of the current post in loading and rendering content for users on different devices. Faster page speeds can be important for SEO rankings because search engines (like Google) consider page speed as a ranking factor.', this.$td),
				suggestedChangesCard    : this.$t.__('Suggested Changes', this.$td),
				suggestedChangesTooltip : this.$t.__('The suggested changes below are generated by TruSEO to help identify areas where the current post can be optimized to improve rankings in search results.', this.$td),
				linkAssistantCard       : this.$t.__('Link Assistant', this.$td),
				linkAssistantTooltip    : this.$t.__('There are many types of links that can be used on a website and each can have a different impact on search engine optimization (SEO). Below are a list of internal, external and affiliate links related to the current post.', this.$td),
				redirectsCard           : this.$t.__('Redirects', this.$td),
				redirectsTooltip        : this.$t.sprintf(
					// Translators: 1 - Plugin Short Name ("AIOSEO").
					this.$t.__('A redirect is a way to send users and search engines to a different URL than the one they originally requested. There are many types of redirects that can be used and each type of redirect has its own set of SEO challenges that should be considered when using them. Below are redirects for the current post that are managed by %1$s.', this.$td),
					import.meta.env.VITE_SHORT_NAME
				),
				seoPerformanceCard    : this.$t.__('SEO Performance', this.$td),
				seoPerformanceTooltip : this.$t.__('The following graph shows the SEO performance of the current post and how well it is ranking in search results and how that ranking has changed over time. This graph can show any significant events or changes that have occurred that may have affected the posts SEO performance, such as updates to the posts content or the implementation of new SEO strategies. Use this graph to identify trends and patterns in the posts performance and make informed decisions on how to improve rankings.', this.$td),
				keywordsCard          : this.$t.__('Keywords', this.$td),
				keywordsTooltip       : this.$t.__('The following table contains keywords that this post has ranked for in the selected timeframe. You can use this table to help you make informed decisions on which keywords to target in your content strategy. The Top Winning list contains keywords where your content has improved in rankings and the Top Losing list contains keywords where your content has declined in rankings.', this.$td)
			}
		}
	},
	computed : {
		seoPerformanceSeries () {
			const data  = this.data.postDetail.seoStatistics
			if (!data) {
				return []
			}

			const statistics = data.statistics
			const graph      = data.intervals

			return [
				{
					name   : this.$t.__('Search Impressions', this.$td),
					data   : graph.map((tick) => ({ x: tick.date, y: tick.impressions || 0 })),
					legend : {
						total : statistics.impressions || 0
					}
				},
				{
					name   : this.$t.__('Search Clicks', this.$td),
					data   : graph.map((tick) => ({ x: tick.date, y: tick.clicks || 0 })),
					legend : {
						total : statistics.clicks || 0
					}
				}
			]
		}
	}
}